services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GITHUB_SERVICE_GITHUB_TOKEN=${GITHUB_SERVICE_GITHUB_TOKEN}
      - CONFIG_FILE=/app/config.yaml
      - GITHUB_SERVICE_DATABASE_HOST=db
      - GITHUB_SERVICE_DATABASE_PORT=5432
      - GITHUB_SERVICE_DATABASE_USER=github_service
      - GITHUB_SERVICE_DATABASE_PASSWORD=github_service_password
      - GITHUB_SERVICE_DATABASE_NAME=github_service_db
      - GITHUB_SERVICE_DATABASE_SSLMODE=disable
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=github_service
      - POSTGRES_PASSWORD=github_service_password
      - POSTGRES_DB=github_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U github_service -d github_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
